FROM postgres:10.10

env http_proxy "http://192.168.20.3:8213"
env https_proxy "http://192.168.20.3:8213"

RUN echo "en_US.UTF-8 UTF-8"> /etc/locale.gen
RUN locale-gen

ADD sources.list /etc/apt/

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6ED0E7B82643E131

RUN sh -c 'echo "" > /etc/apt/sources.list.d/pgdg.list'
RUN apt-get update

RUN apt-get -y install apt-transport-https
RUN sh -c 'echo "deb http://apt-archive.postgresql.org/pub/repos/apt/ stretch-pgdg main 10" > /etc/apt/sources.list.d/pgdg.list'
RUN apt-get update


RUN apt-get -y install libsybdb5 freetds-dev freetds-common libpq-dev git make gcc curl ca-certificates

RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
# RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'


RUN apt-get update
RUN apt-get -y install postgresql-server-dev-10


RUN git clone -q https://github.com/tds-fdw/tds_fdw.git tds_fdw
WORKDIR tds_fdw
RUN make USE_PGXS=1
RUN make USE_PGXS=1 install

env http_proxy ""
env https_proxy ""
RUN apt-get -y remove git make curl gcc
